# Generated by Django 5.1.6 on 2025-03-11 11:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='vin_number',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='VIN-номер должен состоять из 17 символов (латинские буквы и цифры), без I, O, Q.', regex='^[A-HJ-NPR-Z0-9]{17}$')]),
        ),
    ]
