# Generated by Django 5.1.6 on 2025-03-11 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_vin_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Название цвета должно содержать только буквы', regex='^[A-Za-z\\s-]+$')]),
        ),
    ]
